SecRuleEngine On

SecRequestBodyAccess On
SecResponseBodyAccess Off

SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 1048576

SecAuditEngine RelevantOnly
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/nginx/modsec_audit.log
